spring:
	datasource:
		url:jdbc:mysql://localhost:3306/bands_database
		username:root
		password:
	jpa:
		hibernate:
			ddl-auto:update
		database-platform:org.hibernate.dialect.MySQL5InnoDBDialect
		database:mysql
		show-sql:true
		properties:
			hibernate:
				format_sql:true
	data:
		rest:
			base-path:/api